from typing import List, Tuple

SUPPORTED_EXTENSIONS = {".jpg", ".jpeg"}
DREAMSTIME_MAX_KEYWORDS = 50
METADATA_HEADERS = [
    "filename",
    "title",
    "description",
    "keywords",
    "category",
    "purpose",
]

DREAMSTIME_CATEGORY_RULES: List[Tuple[int, List[str]]] = [
    (168, ["animal", "bird", "duck", "dog", "cat", "wildlife", "pet", "insect"]),
    (31, ["bird"]),
    (30, ["pet"]),
    (146, ["landscape", "scenery", "vista", "nature"]),
    (16, ["river", "lake", "stream"]),
    (19, ["ocean", "sea", "coast"]),
    (15, ["mountain"]),
    (25, ["flower", "garden", "blossom"]),
    (12, ["plant", "tree", "vegetation"]),
    (171, ["water"]),
    (123, ["active", "activity"]),
    (162, ["portrait", "headshot"]),
    (119, ["child", "children", "kid"]),
    (117, ["man", "male"]),
    (116, ["woman", "female"]),
    (118, ["family", "families"]),
    (75, ["business people", "office people"]),
    (80, ["finance", "money", "banking"]),
    (79, ["communications", "meeting", "presentation"]),
    (71, ["building", "architecture"]),
    (73, ["interior", "indoor", "room"]),
    (72, ["outdoor"]),
    (70, ["landmark"]),
    (127, ["food", "meal", "dish", "cuisine", "eat"]),
    (137, ["fruit", "vegetable"]),
    (157, ["sport", "fitness", "yoga", "soccer", "basketball", "recreation"]),
    (98, ["transport", "car", "bus", "train", "plane", "boat", "vehicle"]),
    (105, ["computer", "laptop", "desktop", "software"]),
    (104, ["telecommunications", "phone", "mobile"]),
    (210, ["artificial intelligence", "ai"]),
    (92, ["medical", "health", "healthcare", "doctor", "hospital"]),
    (150, ["education", "school", "student", "classroom"]),
    (128, ["religion", "religious", "spiritual", "faith"]),
    (112, ["background", "texture", "pattern"]),
    (199, ["web background", "web texture"]),
    (145, ["object", "still life", "item"]),
    (152, ["retro", "vintage"]),
    (61, ["travel", "destination", "tourism", "vacation"]),
    (190, ["christmas"]),
    (193, ["easter"]),
    (192, ["halloween"]),
    (189, ["new year"]),
]
